### PR TITLE
Issue #2818727 by killua99: Fix incorrect project dependency in file_entity.info.yml

### PR DESCRIPTION
**Pull request by killua99**
Trying to use file_entity with Drupal 8.2 is quite impossible, the dependencies are broken.

### CODE REVIEW

**Comment by dawehner** [comment]
Mh, what is the reason for that? 

```

~/w/d/modules (2468045) $ ag "\- core:"
~/w/d/modules (2468045) $ ag "\- drupal:"
entity_browser/modules/example/entity_browser_example.info.yml
8:  - drupal:views
9:  - drupal:field
10:  - drupal:file
11:  - drupal:node

jsonapi/jsonapi.info.yml
7:  - drupal:system (>=8.2)

media_entity/media_entity.info.yml
7:  - drupal:image
8:  - drupal:user
9:  - drupal:views
11:  - drupal:system (>=8.1.0)

metatag/metatag.info.yml
7:  - drupal:field

search_api/search_api_db/search_api_db_defaults/search_api_db_defaults.info.yml
7:  - drupal:comment
8:  - drupal:field
9:  - drupal:image
10:  - drupal:node
11:  - drupal:text
12:  - drupal:user
13:  - drupal:views

search_api/tests/search_api_test_example_content/search_api_test_example_content.info.yml
6:  - drupal:entity_test

search_api/tests/search_api_test_extraction/search_api_test_extraction.info.yml
6:  - drupal:entity_test

search_api/tests/search_api_test_views/search_api_test_views.info.yml
8:  - drupal:node
9:  - drupal:taxonomy
10:  - drupal:views

search_api_solr/search_api_solr_defaults/search_api_solr_defaults.info.yml
7:  - drupal:comment
8:  - drupal:text
9:  - drupal:field
10:  - drupal:image
11:  - drupal:node
12:  - drupal:user
13:  - drupal:views

search_api_solr/tests/modules/search_api_solr_test_facets/search_api_solr_test_facets.info.yml
7:  - drupal:node
8:  - drupal:taxonomy
9:  - drupal:views

```

All those places use a different way to specify the dependencies. Maybe you are doing composer wrong somehow

**Comment by killua99** [comment]
First thing.

It's like the documentation is written. https://www.drupal.org/node/542202#dependencies

Second, you have an open issue https://www.drupal.org/node/2818727 that we can not update easily Drupal 8.2 using simple `composer require drupal/file_entity` 

It's nothing wrong the way I'm writing my composer.json because I can not even download the module via composer.

EDIT:

Also all these example use `- drupal:node` not `- core:node`

**Comment by Berdir** [comment]
You think you misunderstood @dawehner, I honestly don't exactly get his first sentence but his data is confirming your patch, so I think he's asking why core: was used, not why drupal: was used.

This was introduced in https://www.drupal.org/node/2809301

Your change looks good, but to be able to merge it, it would be good if your commit message followed what is suggested. Based on the title update that I just did, I would suggest "git commit -m 'Issue #2818727 by killua99: Fix incorrect project dependency in file_entity.info.yml'" you can use --amend on your existing commit.

**Comment by killua99** [comment]
I'm gonna do the push with the new message soon (after I recover better internet connection)

**Comment by slashrsm** [comment]
Merged. Thanks!

**Pull request merged**
